services:
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment: 
      - FLASK_SERVER_ADDR=backend:9091  
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    # this will build the image using the Dockerfile in the flask directory
    build:
      context: flask
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    volumes:
      - ./flask:/src
    stop_signal: SIGINT
    # set environment variabla up
    environment:
      - FLASK_SERVER_PORT=9091
      - DB_HOST=mongo
    # the service need to wait until db is up
    depends_on:
      - mongo  

  mongo:
    image: mongodb/mongodb-community-server:7.0-ubi8
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
